<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>L2D</AssemblyName>
        <RootNamespace>L2D</RootNamespace>
        <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DefineConstants>TRACE</DefineConstants>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE</DefineConstants>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
      <PackageReference Include="NativeFileDialogSharp" Version="0.6.0-alpha" />
      <PackageReference Include="Serilog" Version="4.3.1-dev-02406" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
      <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Input.Extensions" Version="2.23.0" />
      <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
      <PackageReference Include="StbImageWriteSharp" Version="1.16.7" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\Codicons.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Bold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-BoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-ExtraBold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-ExtraBoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-ExtraLight.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-ExtraLightItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Italic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Light.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-LightItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Medium.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-MediumItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Regular.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-SemiBold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-SemiBoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-Thin.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMono-ThinItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Bold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-BoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-ExtraBold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-ExtraBoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-ExtraLight.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-ExtraLightItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Italic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Light.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-LightItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Medium.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-MediumItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Regular.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-SemiBold.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-SemiBoldItalic.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-Thin.ttf" />
      <EmbeddedResource Include="Resources\JetBrainsMonoNL-ThinItalic.ttf" />
      <EmbeddedResource Include="Resources\Icon.ico" />
      <EmbeddedResource Include="Resources\Icon.png" />
    </ItemGroup>

</Project>
